#!/usr/bin/php
<?php
/**
* meteor_crud.php
*
* This file will be responsible for handling the parameters received.
*
* @author     David Silva
* @version    0.0.2
*/

// Include Generator File
include_once('app/generator.php');

// Get command line params
$schema_path = $argv[1];

// run generator
run($schema_path);
